services:
    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:80"  # Exposer le port 80 du conteneur sur le port 8000 de l'hôte
        volumes:
            - .:/var/www/html
        env_file:
            - .env  # Utilisation d'un fichier .env pour les variables sensibles
        depends_on:
            - mysql
        networks:
            - internal_network  # Isoler le service Laravel sur un réseau interne

    mysql:
        image: mysql:8.0
        container_name: dbmysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Admin@1234
            MYSQL_DATABASE: TaskListDB
            MYSQL_USER: devuser
            MYSQL_PASSWORD: Dev@Test@1234
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - internal_network  # Réseau interne pour limiter l'accès

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin_db
        restart: always
        ports:
            - "8080:80"  # Exposer phpMyAdmin sur le port 8080
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: Admin@1234
        depends_on:
            - mysql
        networks:
            - internal_network  # Isoler phpMyAdmin sur le même réseau interne

networks:
    internal_network:
        driver: bridge  # Créer un réseau isolé pour les services

volumes:
    mysql_data:
