name: SSH Access Test via VPN

on:
  push:
    branches:
      - master

jobs:
  test-ssh-access:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Installer WireGuard
      - name: Installer WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf

      # Étape 2 : Décoder la configuration WireGuard
      - name: Décoder la configuration WireGuard
        run: |
          echo "${{ secrets.WG_CONFIG }}" | base64 --decode > wg0.conf
          sudo mv wg0.conf /etc/wireguard/

      # Étape 3 : Activer le VPN WireGuard
      - name: Activer le VPN WireGuard
        run: |
          sudo wg-quick up wg0

      # Étape 4 : Charger la clé privée SSH
      - name: Charger la clé privée SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Clé privée stockée dans les secrets GitHub

      # Étape 5 : Ajouter l'empreinte du serveur à known_hosts
      - name: Ajouter le serveur à known_hosts
        run: |
          ssh-keyscan -H -p 2823 192.168.10.211 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Étape 6 : Tester la connexion SSH via le VPN
      - name: Tester la connexion SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 2823 adminserver@192.168.10.211 "echo 'Connexion SSH réussie via VPN !' >> /home/adminserver/github.txt"
